# Generated by Django 4.2 on 2023-10-01 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand_Name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='image')),
            ],
            options={
                'verbose_name_plural': '2. Brands',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image')),
                ('Sale', models.IntegerField()),
                ('Discount_deal', models.CharField(choices=[('Hot Deals', 'Hot Deals'), ('New Arraivels', 'New Arraivels')], max_length=100)),
                ('Discount', models.IntegerField()),
                ('Link', models.CharField(max_length=250, null=True)),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.brand')),
            ],
            options={
                'verbose_name_plural': '1. Slider',
            },
        ),
    ]
