# Generated by Django 4.2 on 2023-10-08 08:52

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_category_main_category_alter_banner_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': '7. Section',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image')),
                ('product_name', models.CharField(max_length=250, null=True)),
                ('total_quantity', models.IntegerField()),
                ('total_availability', models.IntegerField()),
                ('sort_description', ckeditor.fields.RichTextField()),
                ('description', ckeditor.fields.RichTextField()),
                ('model_name', models.CharField(max_length=100)),
                ('price', models.ImageField(upload_to='')),
                ('discount', models.ImageField(upload_to='')),
                ('tags', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sub_category')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.section')),
            ],
            options={
                'db_table': 'app_Product',
            },
        ),
    ]
